import NavBar from "./NavBar/NavBar";
import Filter from "./Filter/Filter";
import Error from "./Error/Error";
import Loader from "./Loader/Loader";
import Model from "./Model/Model";
import UserCard from "./UserCard/UserCard";
import FriendRequestCard from "./UserCard/FriendRequestCard";
import Friend from "./Friend/Friend";
import Register from "../pages/UserRegister";
import Login from "../pages/login";
import Mnem from "./Mnem/Mnem";
import Forgot from "../pages/Forgot";
export { NavBar, Filter, Error, Loader, Model, UserCard, FriendRequestCard, Friend, Register, Login, Mnem,Forgot};